Repository kthaisociety/website, pull requests merged in 2022-05, with the labels that each got.

#304 Email on cancel/register event on Slack
  messaging/api/slack/register.py
Labels: bug, enhancement

#305 Make Slack user external ID unique
  app/settings.py
  messaging/admin.py
  messaging/migrations/0008_slackuser_external_id_unique.py
  messaging/migrations/0009_slackuser_picture_storage.py
  messaging/models.py
  user/migrations/0032_user_picture_resume_storage.py
  user/models.py
Labels: bug

#306 Add speakers page
  app/static/scss/theme.scss
  app/templates/base.html
  event/templates/event.html
  event/templates/speaker.html
  event/templates/speakers.html
  event/urls.py
  event/views.py
  messaging/api/slack/register.py
Labels: enhancement

#307 Add distinct on speakers page
  event/templates/speaker.html
  event/views.py
Labels: bug

#308 Add distinct
  event/views.py
Labels: bug

#309 Change/social media tree
  app/static/scss/theme.scss
  app/templates/include/link.html
  app/templates/social.html
  app/urls.py
  app/views.py
  page/admin.py
  page/migrations/0004_link.py
  page/models.py
Labels: enhancement

#310 Fix upload media to Twitter
  news/api/fact/twitter.py
Labels: bug
