Repository kthaisociety/website, pull requests merged in 2022-04, with the labels that each got.

#289 Bump up versions
  requirements.txt
Labels: maintenance

#290 Add pins to deprecate featured news
  app/processor.py
  app/templates/home.html
  app/views.py
  news/admin.py
  news/migrations/0007_pin.py
  news/models.py
  news/utils.py
Labels: enhancement

#287 added "become a member" button
  app/static/scss/theme.scss
  app/templates/base.html
  user/models.py
  user/templates/dashboard.html
Labels: enhancement

#292 Board changes
  app/static/scss/theme.scss
  business/models.py
  business/templates/include/offer.html
  business/templates/jobs.html
  business/views.py
Labels: enhancement

#293 Add link on pins
  app/static/scss/theme.scss
  app/templates/home.html
  news/migrations/0008_pin_external_url.py
  news/migrations/0009_pin_external_text.py
  news/models.py
Labels: enhancement

#294 Make pin link text nullable
  news/migrations/0010_pin_external_text_null.py
  news/models.py
Labels: bug

#295 Add Slack model and fix Slack picture profile loop update
  app/slack.py
  app/static/img/mask.png
  app/static/img/mask.xcf
  app/templates/base.html
  messaging/admin.py
  messaging/api/slack/auth.py
  messaging/api/slack/channel.py
  messaging/api/slack/register.py
  messaging/api/slack/user.py
  messaging/migrations/0006_slackuser.py
  messaging/migrations/0007_slackuser_picture_original.py
  messaging/models.py
  user/admin.py
  user/managers.py
  user/migrations/0031_user_remove_slack.py
  user/models.py
  user/templates/dashboard.html
  user/utils.py
Labels: bug, enhancement

#296 Change/versatile image cache
  .github/workflows/django.yml
  app/settings.py
Labels: enhancement

#298 Fix context for posters
  event/views.py
Labels: bug

#299 Fix context for posters
  app/static/fonts/Futura-Bold.ttf
  app/static/fonts/Futura-Medium.ttf
  app/static/fonts/Futura-Regular.ttf
  event/templates/poster/poster.html
Labels: bug

#300 Fix context for posters
  event/templates/poster/poster.html
Labels: bug

#301 Fix session order on poster
  event/templates/poster/poster.html
  event/views.py
Labels: bug

#302 Dynamic poster height
  event/templates/poster/poster.html
Labels: bug

#303 Dynamic poster height
  event/templates/poster/poster.html
Labels: bug
