Repository kthaisociety/website, pull requests merged in 2022-03, with the labels that each got.

#274 Allow external registrations
  event/admin.py
  event/migrations/0031_event_signup_url.py
  event/models.py
  event/templates/include/registration.html
  event/views.py
Labels: enhancement

#275 Post on Slack external signup URL if given
  messaging/api/slack/announcement.py
Labels: bug

#276 Don't react on event announcement if can't Slack signup
  messaging/api/slack/announcement.py
  messaging/api/slack/register.py
Labels: bug

#279 Add Twitter integration with facts every week (by Vilhelm)
  app/settings.py
  news/admin.py
  news/api/fact/post.py
  news/api/fact/twitter.py
  news/consts.py
  news/cron.py
  news/enums.py
  news/migrations/0006_fact_factpost.py
  news/models.py
  requirements.txt
Labels: enhancement

#280 Add Twitter to site
  app/settings.py
  app/variables.py
Labels: enhancement

#278 Blocks registering with a kthais mail account
  app/views.py
  user/views.py
Labels: enhancement

#285 Change jobs email
  app/utils.py
  app/variables.py
  business/templates/jobs.html
  requirements-dev.txt
Labels: maintenance
